spring:
  application:
    name: movie-theater
  datasource:
    username: postgres
    password: postgres
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/quiz-web}
  profiles:
    active: ${PROFILE_ACTIVE:dev-local}
  liquibase:
    change-log: classpath:db/master.xml
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  mail:
    host: smtp.gmail.com
    port: 587
    username: nguyennanhtu143@gmail.com
    password: qxcx yqgy bnhi paqm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:156272986514-3142b1hdt8fghr98t0ectmsgvp0k5fie.apps.googleusercontent.com}
            client-secret: ${GOOGLE_CLIENT_SECRET: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}
            scope:
              - email
              - profile
            redirect-uri: ${GOOGLE_REDIRECT_URI:http://localhost:8888/login/oauth2/code/google}

server:
  port: ${PORT_INTERNAL:8888}

logging:
  level:
    sql: debug

jwt:
  secret-key: b3NpbnRfYXBpX2F1dGhvcml6YXRpb25AMjAyM19hY2Nlc3NfdG9rZW4=
  access-token:
    ttl: 864000000
  refresh-token:
    ttl: 864000000



