spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: hieu112004
    url: jdbc:postgresql://localhost:5432/dh

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
